INSERT INTO `rehber` VALUES ('Sait ', 'ORHAN', 'Yeni mah. Demir sok. no:23/3 KOCASİNAN MERKEZ', '0864567823', 'sait@hotmail.com');
INSERT INTO `rehber` VALUES ('Kasım', 'EKİN', 'gül mah.  sedef sok. no:7 MUŞ ', '0789234566', 'kasim@hotmail.com');
INSERT INTO `rehber` VALUES ('Sait ', 'Mustafa', 'a mah. b sok. no:4 BATMAN', '05432438362', 'sait@gmail.com');
INSERT INTO `rehber` VALUES ('SERDAR', 'Fidan', 'DENİZ MAH. DEFNE SOK. NO:1 KASTAMONU KOZAKLI', '3456782345', 'sila@hotmail.com');
INSERT INTO `rehber` VALUES ('SADIK', 'yağmağan', 'cccccccccccccc mah. aaaaaaaaaaa sok. Batman', '1234567890', 's@hotmail.com');
INSERT INTO `rehber` VALUES ('ayşe', 'hilmet', 'dddddddddddddddd mah. ssssssssssssssssss sok. no:6 İZMİR', '4567897654', 'ayse@hotmail.com');
INSERT INTO `rehber` VALUES ('gaye', 'aksu', 'kkkkkkkkkkkkk mah. fffffffffffffff sok. no:9 ANKARA', '8765433221', 'gaye@gmail.com');
INSERT INTO `rehber` VALUES ('oya', 'bak', 'HHHHHHHHHHH sok. bbbbbbbbbb mah. DENİZLİ', '8767654565', 'oya@gmail.com');
INSERT INTO `rehber` VALUES ('Mehmed', 'Cuma', '?lçe?l', '1234345324', '');
INSERT INTO `rehber` VALUES ('Bilal', 'Babayi?it', '?lçe?l', '1234567890', 'aaaaa@ddd.com');
INSERT INTO `rehber` VALUES ('Bilal', 'baba', '?lçe?l', '1234567890', '');
