/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telefon;


import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.JOptionPane;
/**
 *
 * @author öznur
 */
public class kayitSil extends javax.swing.JFrame {

    /**
     * Creates new form kayitSil
     */
    public kayitSil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtisim2 = new javax.swing.JTextField();
        txtsoyisim2 = new javax.swing.JTextField();
        btnbul = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBulananisim2 = new javax.swing.JLabel();
        lblBulananNumara2 = new javax.swing.JLabel();
        lblBulananMail2 = new javax.swing.JLabel();
        lblBulananAdres2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("İsim: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Soyisim: ");

        btnbul.setText("Bul");
        btnbul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbulActionPerformed(evt);
            }
        });

        jButton1.setText("Kaydı Sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kişi Bilgileri"));

        lblBulananisim2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananisim2.setText("isim");

        lblBulananNumara2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananNumara2.setText("Numara");

        lblBulananMail2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananMail2.setText("mail");

        lblBulananAdres2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananAdres2.setText("Adres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBulananisim2)
                    .addComponent(lblBulananNumara2)
                    .addComponent(lblBulananMail2)
                    .addComponent(lblBulananAdres2))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBulananisim2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBulananNumara2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBulananMail2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBulananAdres2)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtisim2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(txtsoyisim2))
                        .addGap(69, 69, 69)
                        .addComponent(btnbul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtisim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsoyisim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Connection baglan;
    private void btnbulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbulActionPerformed
      try{
         String adi=txtisim2.getText();
         String soyadi=txtsoyisim2.getText();
        
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs1 = komut.executeQuery("SELECT * FROM rehber WHERE isim='"+adi+"' AND soyisim='"+soyadi+"'");
        
       while(rs1.next())
            {
           lblBulananisim2.setText(rs1.getString("isim")  +"  "+ rs1.getString("soyisim") + "\n");
              lblBulananNumara2.setText(rs1.getString("telefon") );
               lblBulananMail2.setText(rs1.getString("mail"));
                lblBulananAdres2.setText(rs1.getString("adres"));
            }
         
   }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
                   
    }//GEN-LAST:event_btnbulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] secenekler = {"Evet","Hayır","Düşünmek İstiyorum"};
        int yanit_alan = JOptionPane.showOptionDialog(this,"Kişinin tüm bilgileri silinecektir. Bu işlem geri alınamaz\nBunu Gerçekleştirmek İstiyor musunuz?", "Basit bir soru :)", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, secenekler, secenekler[1]);
        if(yanit_alan==0)
        {
        try{
         String adi=txtisim2.getText();
         String soyadi=txtsoyisim2.getText();
        
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       komut.executeUpdate("DELETE FROM rehber WHERE isim='"+adi+"' AND soyisim='"+soyadi+"'");
       JOptionPane.showMessageDialog(null, "Kayıt Başarı ile Silinmiştir.");
       this.show(false);
         
   }  
   catch(   ClassNotFoundException | SQLException | HeadlessException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new kayitSil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbul;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBulananAdres2;
    private javax.swing.JLabel lblBulananMail2;
    private javax.swing.JLabel lblBulananNumara2;
    private javax.swing.JLabel lblBulananisim2;
    private javax.swing.JTextField txtisim2;
    private javax.swing.JTextField txtsoyisim2;
    // End of variables declaration//GEN-END:variables
}
