/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telefon;

/**
 *
 * @author Sait
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class telefon_rehberi extends javax.swing.JFrame {

    /**
     * Creates new form telefon_rehberi
     */
    public telefon_rehberi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAranan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtArananisim = new javax.swing.JTextField();
        btnBul = new javax.swing.JButton();
        txtArananSoyisim = new javax.swing.JTextField();
        pnlBulunan = new javax.swing.JPanel();
        lblBulananisim = new javax.swing.JLabel();
        lblBulananAdres = new javax.swing.JLabel();
        lblBulananNumara = new javax.swing.JLabel();
        lblBulananMail = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablo = new javax.swing.JTable();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btnsil = new javax.swing.JButton();
        btnguncelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Telefon Rehberim");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Aradığınız Kişinin Adı - Soyadı: ");

        txtArananisim.setText("İsim");
        txtArananisim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtArananisimMouseClicked(evt);
            }
        });

        btnBul.setText("Ara");
        btnBul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBulActionPerformed(evt);
            }
        });

        txtArananSoyisim.setText("Soyisim");
        txtArananSoyisim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtArananSoyisimMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlArananLayout = new javax.swing.GroupLayout(pnlAranan);
        pnlAranan.setLayout(pnlArananLayout);
        pnlArananLayout.setHorizontalGroup(
            pnlArananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtArananisim, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlArananLayout.createSequentialGroup()
                        .addComponent(txtArananSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArananLayout.setVerticalGroup(
            pnlArananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArananLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArananisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlArananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArananSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBul))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBulananisim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananisim.setText("isim");

        lblBulananAdres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananAdres.setText("Adres");

        lblBulananNumara.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananNumara.setText("Numara");

        lblBulananMail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBulananMail.setText("mail");

        javax.swing.GroupLayout pnlBulunanLayout = new javax.swing.GroupLayout(pnlBulunan);
        pnlBulunan.setLayout(pnlBulunanLayout);
        pnlBulunanLayout.setHorizontalGroup(
            pnlBulunanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBulunanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBulunanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBulananisim)
                    .addComponent(lblBulananNumara)
                    .addComponent(lblBulananMail)
                    .addComponent(lblBulananAdres))
                .addContainerGap(507, Short.MAX_VALUE))
        );
        pnlBulunanLayout.setVerticalGroup(
            pnlBulunanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBulunanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBulananisim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBulananNumara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBulananMail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBulananAdres)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton1.setText("A");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("S");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ç");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("B");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ö");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("C");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("D");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("E");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("T");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Ş");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("G");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("F");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("I");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("İ");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setText("H");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("N");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton20.setText("K");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("P");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("O");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("U");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("R");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("V");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("Z");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("Ü");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Y");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setText("W - X - Q");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        tblTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "İsim ", "Soyisim", "Telefon", "E-mail", "Adres"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTablo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblTabloAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblTablo);

        jButton30.setText("Yeni Kayıt Ekle");
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });

        jButton31.setText("L");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("M");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton18.setText("J");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        btnsil.setText("Kayıt Sil");
        btnsil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsilMouseClicked(evt);
            }
        });
        btnsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsilActionPerformed(evt);
            }
        });

        btnguncelle.setText("Kayıt Güncelle");
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(177, 177, 177)
                                                .addComponent(jButton7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnsil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnguncelle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton17)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButton22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton24)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlAranan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlBulunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAranan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBulunan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton3)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton12)
                    .addComponent(jButton11)
                    .addComponent(jButton16)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton20)
                    .addComponent(jButton17)
                    .addComponent(jButton22)
                    .addComponent(jButton5)
                    .addComponent(jButton21)
                    .addComponent(jButton24)
                    .addComponent(jButton31)
                    .addComponent(jButton32)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton10)
                    .addComponent(jButton9)
                    .addComponent(jButton23)
                    .addComponent(jButton27)
                    .addComponent(jButton25)
                    .addComponent(jButton28)
                    .addComponent(jButton26)
                    .addComponent(jButton29)
                    .addComponent(jButton30)
                    .addComponent(btnsil)
                    .addComponent(btnguncelle))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'f%'");
        
       TabloDoldur(rs2); 
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'o%'");
        
       TabloDoldur(rs2); 
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'ş%'");
        
         TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtArananisimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArananisimMouseClicked
      
    }//GEN-LAST:event_txtArananisimMouseClicked

    private void txtArananSoyisimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArananSoyisimMousePressed
       
    }//GEN-LAST:event_txtArananSoyisimMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblBulananAdres.setText("");
        lblBulananMail.setText("");
        lblBulananNumara.setText("");
        lblBulananisim.setText("");
    }//GEN-LAST:event_formWindowActivated

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
yeniKayit goster = new yeniKayit();
goster.show();;// TODO add your handling code here:
    }//GEN-LAST:event_jButton30MouseClicked
   private Connection baglan; 
  
    private void btnBulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBulActionPerformed
   try{
         String adi=txtArananisim.getText();
         String soyadi=txtArananSoyisim.getText();
        
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       Statement komut = baglan.createStatement();
       ResultSet rs1 = komut.executeQuery("SELECT * FROM rehber WHERE isim='"+adi+"' AND soyisim='"+soyadi+"'");
        //ResultSet sonuc = komut.executeQuery("SELECT COUNT(*) FROM rehber WHERE isim='"+txtArananisim.getText()+"' AND soyisim='"+txtArananSoyisim.getText()+"'");
          //      sonuc.next();
            //    int sayi = sonuc.getInt(1);
              //  if(sayi>0)
               // {
       while(rs1.next())
            {
            lblBulananisim.setText(rs1.getString("isim")  +" "+ rs1.getString("soyisim") + "\n");
              lblBulananNumara.setText(rs1.getString("telefon") );
               lblBulananMail.setText(rs1.getString("mail"));
                lblBulananAdres.setText(rs1.getString("adres"));
            }
             //   else
               //     JOptionPane.showMessageDialog(null, "Aranan isimde kayıt bulunmamaktadır.");
         
   }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    }//GEN-LAST:event_btnBulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'a%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
         
    }//GEN-LAST:event_jButton1ActionPerformed
    
private void tblTabloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblTabloAncestorAdded
 
}//GEN-LAST:event_tblTabloAncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'b%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'c%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'ç%'");
        TabloDoldur(rs2);
       
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'd%'");
        
       TabloDoldur(rs2); 
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'e%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'g%'");
        
       TabloDoldur(rs2);  
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'h%'");
        
       TabloDoldur(rs2); 
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'ı%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'i%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'j%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'k%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'L%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'm%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'n%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'ö%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(Exception hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'p%'");
        
          TabloDoldur(rs2);
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'r%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 's%'");
        
        TabloDoldur(rs2); 
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 't%'");
         TabloDoldur(rs2); 
       
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'u%'");
        
       TabloDoldur(rs2);
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'ü%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'v%'");
        
        TabloDoldur(rs2);
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'y%'");
         TabloDoldur(rs2);
       
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'z%'");
     
       TabloDoldur(rs2);  
         
} 
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
  try{
         
            Class.forName("com.mysql.jdbc.Driver");
       
       baglan = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehberim","root","2569");
       
       Statement komut = baglan.createStatement();
       ResultSet rs2 = komut.executeQuery("SELECT * FROM rehber WHERE isim LIKE 'w%' OR 'X%' OR 'Q%'");
       
      
        
        
            TabloDoldur(rs2); 
         
          }  
   catch(ClassNotFoundException | SQLException hata)
           {
              JOptionPane.showMessageDialog(rootPane, hata.toString());
           }
    
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
        guncelle guncelleme = new guncelle();
        guncelleme.show();
    }//GEN-LAST:event_btnguncelleActionPerformed

    private void btnsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsilActionPerformed
       
    }//GEN-LAST:event_btnsilActionPerformed

    private void btnsilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsilMouseClicked
      kayitSil nesne= new kayitSil();
      nesne.show();// TODO add your handling code here:
    }//GEN-LAST:event_btnsilMouseClicked
 public void TabloDoldur(ResultSet rs2) {
try {
        
      myTableModel model = new myTableModel(rs2); //Tablomuza model oluştur
    tblTablo.setModel(model); //Tabloyu res'teki kayıtlar ile doldur
     if(tblTablo.getRowCount()==0)
          JOptionPane.showConfirmDialog(null, "Aranan isimde kayıt bulunmamaktadır.","OOOPPPSSS ;)", JOptionPane.WARNING_MESSAGE);
} 
catch (Exception e) {
    JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
}
}
   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telefon_rehberi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telefon_rehberi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telefon_rehberi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telefon_rehberi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new telefon_rehberi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBul;
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btnsil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBulananAdres;
    private javax.swing.JLabel lblBulananMail;
    private javax.swing.JLabel lblBulananNumara;
    private javax.swing.JLabel lblBulananisim;
    private javax.swing.JPanel pnlAranan;
    private javax.swing.JPanel pnlBulunan;
    private javax.swing.JTable tblTablo;
    private javax.swing.JTextField txtArananSoyisim;
    private javax.swing.JTextField txtArananisim;
    // End of variables declaration//GEN-END:variables
}
